# Generated by Django 5.0.6 on 2024-07-02 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_customuser_created_customuser_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
