# Generated by Django 5.0.6 on 2024-07-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_customuser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
