# Generated by Django 5.0.6 on 2024-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0002_category_created_category_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='entry',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tag',
            field=models.ManyToManyField(to='journal_api.tag'),
        ),
    ]
