# Generated by Django 5.0.6 on 2024-07-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0003_remove_tag_entry_journalentry_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='tag',
            new_name='tags',
        ),
    ]
