# Generated by Django 5.0.6 on 2024-07-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_api', '0004_rename_tag_journalentry_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.TextField(unique=True),
        ),
    ]
